# Generated by Django 4.2 on 2023-08-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='multipleimageupload',
            name='images',
            field=models.ImageField(default=[], max_length=255, null=True, upload_to='multiple_images/'),
        ),
        migrations.AddField(
            model_name='multipleimageupload',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
    ]
